create database bankmanagementsystem;
use bankmanagementsystem;
drop table signup;
drop table signuptwo;
drop table signupthree;
drop table login;
drop table bank;
create table signup(formno varchar(20), name varchar(20), fname varchar(20), dob varchar(20), gender varchar(20),email varchar(30), marital varchar(20), address varchar(40), city varchar(25), pincode varchar(20), state varchar(25),mobileno int);
create table signuptwo(formno varchar(20), religion varchar(20), category varchar(20), income varchar(20), education varchar(20), occupation varchar(20), pan varchar(20), aadhar varchar(20), scitizen varchar(20), eaccount varchar(20));
create table signupthree(formno varchar(20), accountType varchar(40), cardnumber varchar(25), pin varchar(10), facility varchar(100)); 
create table login(formno varchar(20), cardno varchar(25), pin varchar(10));
create table bank(pin varchar(10), date varchar(50), type varchar(20), amount varchar(20));
select * from bank;
select * from login;